version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: teste_loja_abc_api_db
      MYSQL_ROOT_PASSWORD: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
